# Generated by Django 5.2.14 on 2026-05-28 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="document",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="chunk",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="chunks", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="analysisresult",
            name="document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="analysis_results", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="documentrelation",
            name="source_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="relations_as_source", to="documents.document"
            ),
        ),
        migrations.AddField(
            model_name="documentrelation",
            name="target_document",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="relations_as_target", to="documents.document"
            ),
        ),
        migrations.AddIndex(
            model_name="chunk",
            index=models.Index(fields=["document", "position"], name="documents_c_documen_0c032e_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="documentrelation",
            unique_together={("source_document", "target_document", "relation_type")},
        ),
    ]
