# Generated by Django 5.2.14 on 2026-05-28 16:54

import pgvector.django.vector
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("documents", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalysisResult",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("result_type", models.CharField(max_length=100)),
                ("content", models.JSONField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Chunk",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("content", models.TextField()),
                (
                    "chunk_type",
                    models.CharField(
                        choices=[
                            ("paragraph", "Paragraph"),
                            ("clause", "Contract Clause"),
                            ("xml_block", "XML Block"),
                            ("function", "Function"),
                            ("class", "Class"),
                            ("api_endpoint", "API Endpoint"),
                            ("markdown_section", "Markdown Section"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=30,
                    ),
                ),
                ("position", models.IntegerField()),
                ("page_number", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("embedding", pgvector.django.vector.VectorField(blank=True, dimensions=768, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["document", "position"],
            },
        ),
        migrations.CreateModel(
            name="Document",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=512)),
                ("file", models.FileField(upload_to="documents/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("markdown", "Markdown"),
                            ("xml", "XML"),
                            ("code", "Source Code"),
                            ("openapi", "OpenAPI Spec"),
                            ("text", "Plain Text"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("content_hash", models.CharField(db_index=True, max_length=64, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DocumentRelation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "relation_type",
                    models.CharField(
                        choices=[
                            ("referenziert", "Referenziert"),
                            ("erweitert", "Erweitert"),
                            ("widerspricht", "Widerspricht"),
                            ("aehnlich", "Ähnlich"),
                            ("gehoert_zu", "Gehört zu"),
                            ("basiert_auf", "Basiert auf"),
                        ],
                        max_length=30,
                    ),
                ),
                ("confidence", models.FloatField(default=1.0)),
                ("created_by", models.CharField(default="system", max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
